version: '3'
services:
  frontend:
    container_name: example-frontend
    image: example-frontend
    build:
      context: ../../part1/e1.12/example-frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  backend:
    container_name: example-backend
    image: example-backend
    build:
      context: ../../part1/e1.13/example-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis  # required by the exercise only host name
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: postgres

  redis:
    image: redis
    ports:
      - 6379:63779
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_example
    volumes:
      - database:/var/lib/postgresql/data
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
      

volumes:
  redis_data:
  database: