version: '3'
services:
  frontend:
    container_name: hello-frontend
    image: hello-frontend
    build:
      context: ../../part1/e1.12/example-frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  backend:
    container_name: hello-backend
    image: hello-backend
    build:
      context: ../../part1/e1.13/example-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080